version: '3.4'
services:
  sut:
    image: pharo-runtime:sut
    command: pharo metacello install github://ba-st/Buoy:release-candidate BaselineOfBuoy --groups=Deployment
    ulimits:
      rtprio:
        soft: 2
        hard: 2
