version: '3.4'
services:
  date:
    image: pharo-date:sut
    labels:
      traefik.enable: 'true'
      traefik.http.routers.date.rule: "HostRegexp:{catchall:.*}"
      traefik.http.services.date.loadbalancer.server.port: 8080
    ulimits:
      rtprio:
        soft: 2
        hard: 2
    deploy:
      replicas: 3

  balancer:
    image: traefik:v2.10
    command:
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"      
      - "--entrypoints.web.address=:80"
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
