version: '3.4'
services:
  date:
    image: pharo-date:sut
    labels:
      traefik.port: 8080
      traefik.frontend.rule: "HostRegexp:{catchall:.*}" # Match all requests
    ulimits:
      rtprio:
        soft: 2
        hard: 2
    deploy:
      replicas: 3
  balancer:
    # See https://docs.traefik.io/configuration/backends/docker/
    image: traefik:v1.7
    command: --docker --docker.watch
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro # Required because of docker backend, so traefik can get docker data.
